# Used globally
baseDomain: "https://dmlive.wiki"

# Used by the information template
wikiPath: "" # If you do not provide this field, it defaults to "baseDomain/wiki"
footer: "(*) indicates lead vocals by Martin Gore\n\nRecording freely provided by the Depeche Mode Live Wiki: https://dmlive.wiki"

# Used by the wiki template
streamPath: "https://media.dmlive.wiki/stream"
downloadPath: "" # If you do not provide this field, it defaults to "baseDomain/downloads"
